name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Git repository
        run: git init

      - name: Install and configure SSH
        run: |
          if ! which ssh-agent; then
            sudo apt-get update -y
            sudo apt-get install openssh-client -y
          fi

          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")

          mkdir -p ~/.ssh
          if [[ -f /.dockerenv ]]; then
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          fi

      - name: Add production remote
        run: git remote add production ssh://uid3356570@shell.websupport.cz:20766/home/repos/snipe-construction.git
      - name: Push to production
        run: git push production HEAD:master
